// Users
const GET_ME = 'GET_ME';
const SET_USERS = 'SET_USERS';

// CAPABILITIES
const GET_CAPABILITIES = 'GET_CAPABILITIES';
const SET_LOADING_ME_CAPABILITIES = 'SET_LOADING_ME_CAPABILITIES';

// DASHBOARD
const SET_LOADING_DASHBOARD = 'SET_LOADING_DASHBOARD';
const SET_DASHBOARD = 'SET_DASHBOARD';
const SET_ERROR_CONTRACT_DASHBOARD = 'SET_ERROR_CONTRACT_DASHBOARD';

// APPLICATIONS
const SET_APPLICATIONS_DATA = 'SET_APPLICATIONS_DATA';
const APPLICATIONS_DEFAULT_TOP = 50;
const APPLICATIONS_DEFAULT_SKIP = 0;

// WORKFLOWS
const SET_WORKFLOWS = 'SET_WORKFLOWS';
const SET_ERROR_WORKFLOWS = 'SET_ERROR_WORKFLOWS';
const SET_LOADING_WORKFLOWS = 'SET_LOADING_WORKFLOWS';
const WORKFLOWS_DEFAULT_TOP = 50;
const WORKFLOWS_DEFAULT_SKIP = 0;

// CONTRACTS
const CONTRACTS_DEFAULT_TOP = 50;
const CONTRACTS_DEFAULT_SKIP = 0;
const SET_WORKFLOW_CONTRACTS = 'SET_WORKFLOW_CONTRACTS';

// DASHBOARD
const SET_CONTRACT_DASHBOARD_CONSTRUCTOR = 'SET_CONTRACT_DASHBOARD_CONSTRUCTOR';
const SET_COLUMN_PROPS = 'SET_COLUMN_PROPS';
const SET_CURRENT_WEATHER = 'SET_CURRENT_WEATHER';
const CLEAR_CONTRACT_DASHBOARD = 'CLEAR_CONTRACT_DASHBOARD';

// NAVIGATION
const SAVE_APPLICATION_ID = 'SAVE_APPLICATION_ID';
const SAVE_WORKFLOW_ID = 'SAVE_WORKFLOW_ID';
const SAVE_WORKFLOWINSTANCE_ID = 'SAVE_WORKFLOWINSTANCE_ID';

// VIEW
const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';

export {
  GET_ME,
  GET_CAPABILITIES,
  SET_LOADING_ME_CAPABILITIES,
  SET_LOADING_DASHBOARD,
  SET_DASHBOARD,
  SET_ERROR_CONTRACT_DASHBOARD,
  SET_APPLICATIONS_DATA,
  APPLICATIONS_DEFAULT_SKIP,
  APPLICATIONS_DEFAULT_TOP,
  SET_WORKFLOWS,
  SET_ERROR_WORKFLOWS,
  SET_LOADING_WORKFLOWS,
  WORKFLOWS_DEFAULT_TOP,
  WORKFLOWS_DEFAULT_SKIP,
  CONTRACTS_DEFAULT_SKIP,
  CONTRACTS_DEFAULT_TOP,
  SET_WORKFLOW_CONTRACTS,
  SET_CONTRACT_DASHBOARD_CONSTRUCTOR,
  SET_COLUMN_PROPS,
  SET_CURRENT_WEATHER,
  SET_USERS,
  SAVE_APPLICATION_ID,
  SAVE_WORKFLOW_ID,
  SAVE_WORKFLOWINSTANCE_ID,
  SET_CURRENT_VIEW,
  CLEAR_CONTRACT_DASHBOARD,
};
